const handleError = (e) => {
    console.log("Something went wrong: ", e)
}

module.exports = handleError