const handleError = (e) => {
    console.log("Something went wrong: ", e.message)
}

module.exports = handleError